version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${PORT}:${PORT}
    expose:
      - "${PORT}"
